"""Export adapters: JSON, PDF and a FHIR-*compatible* JSON bundle.

The FHIR adapter produces resources shaped according to FHIR R4 for the subset
MedScribe populates. It is deliberately described as "FHIR-compatible": it has
not been validated against a conformance server, and no claim of full compliance
is made.
"""

from __future__ import annotations

import io
import json
import re
import uuid
from datetime import datetime, timezone
from typing import Any

from app.models.enums import EntityStatus, EntityType
from app.schemas.clinical import SECTION_KEYS, SECTION_LABELS, ClinicalNoteContent

FHIR_VERSION = "4.0.1"
DISCLAIMER = (
    "Generated by VoiceScribe AI. Not a diagnostic record. AI-assisted documentation "
    "requires human review; model confidence is not a measure of clinical correctness."
)


_UNDOCUMENTED_PHRASES = {
    "not mentioned",
    "not found",
    "not stated",
    "not discussed",
    "none mentioned",
    "not available",
    "n/a",
    "na",
    "none",
    "unknown",
}


def _section_documented(section: dict[str, Any] | None) -> bool:
    text = str((section or {}).get("text") or "").strip()
    return bool(text) and text.lower() not in _UNDOCUMENTED_PHRASES


def build_export_payload(
    *,
    session: dict[str, Any],
    note: dict[str, Any],
    segments: list[dict[str, Any]],
    entities: list[dict[str, Any]],
    evidence: list[dict[str, Any]],
    versions: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    return {
        "export_format": "VOICESCRIBE_JSON_V1",
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "disclaimer": DISCLAIMER,
        "session": session,
        "clinical_note": note,
        "transcript": segments,
        "clinical_entities": entities,
        "evidence_links": evidence,
        "note_versions": versions or [],
    }


def export_json(payload: dict[str, Any]) -> bytes:
    return json.dumps(payload, indent=2, default=str).encode("utf-8")


def _extract_doctor_prescriptions(
    content: dict[str, Any],
    entities: list[dict[str, Any]],
    segments: list[dict[str, Any]],
    appt_date: str,
) -> list[dict[str, str]]:
    """Extract ONLY doctor-prescribed medications for the encounter prescription table.
    
    Excludes medications taken by the patient prior to visit, chronic regular medications,
    or medications discussed solely during doctor inquiry without prescription.
    """
    segment_map = {str(s.get("ref")): s for s in segments if s.get("ref")}

    plan_sec = content.get("plan") or {}
    plan_text = str(plan_sec.get("text") or "").strip()
    follow_sec = content.get("follow_up") or {}
    follow_text = str(follow_sec.get("text") or "").strip()
    full_plan_text = f"{plan_text} {follow_text}".strip()

    curr_med_text = str((content.get("current_medication") or {}).get("text") or "").lower()
    tx_hist_text = str((content.get("treatment_history") or {}).get("text") or "").lower()
    hpi_text = str((content.get("history_of_present_illness") or {}).get("text") or "").lower()

    prior_phrases = [
        "before coming", "before visit", "at home", "prior to", "already taking",
        "have been taking", "took yesterday", "past medication", "otc", "self medicat",
        "home treatment", "regularly taking", "regular medication"
    ]

    dose_pattern = r"(\d+(?:\.\d+)?\s*(?:mg|g|mcg|ml|iu|units?|tablets?|tabs?|caps?))"
    freq_pattern = r"\b(1-0-1|0-1-0|1-1-1|0-0-1|1-0-0|0-1-1|1-1-0|OD|BD|TDS|QID|SOS|HS|PRN|STAT|once daily|twice daily|thrice daily|three times a day|twice a day|once a day|every \d+ hours?|as needed)\b"
    dur_pattern = r"\b((?:for\s+)?\d+\s*(?:days?|weeks?|months?)|x\s*\d+\s*(?:days?|weeks?))\b"

    prescriptions: list[dict[str, str]] = []
    seen_drugs: set[str] = set()

    def parse_sig(text_snippet: str) -> tuple[str, str, str, str]:
        dosage = "As directed"
        freq = "As prescribed"
        dur = "As directed"
        route = "Oral"

        dm = re.search(dose_pattern, text_snippet, re.IGNORECASE)
        if dm:
            dosage = dm.group(1).strip()
        fm = re.search(freq_pattern, text_snippet, re.IGNORECASE)
        if fm:
            freq = fm.group(1).strip()
        durm = re.search(dur_pattern, text_snippet, re.IGNORECASE)
        if durm:
            dur = durm.group(1).strip()
        if re.search(r"\b(topical|ointment|cream|gel)\b", text_snippet, re.IGNORECASE):
            route = "Topical"
        elif re.search(r"\b(iv|intravenous)\b", text_snippet, re.IGNORECASE):
            route = "IV"
        elif re.search(r"\b(im|intramuscular)\b", text_snippet, re.IGNORECASE):
            route = "IM"
        elif re.search(r"\b(drops?|eye\s+drops?|ear\s+drops?)\b", text_snippet, re.IGNORECASE):
            route = "Drops"
        return dosage, freq, route, dur

    # 1. Process medication entities from clinical_entities
    med_entities = [e for e in entities if str(e.get("entity_type")).upper() == "MEDICATION" and e.get("value")]
    for med in med_entities:
        med_val = str(med.get("value") or "").strip()
        if not med_val:
            continue
        med_lower = med_val.lower()

        status = str(med.get("status", "")).upper()
        if status in ("HISTORICAL", "NEGATED", "PAST"):
            continue

        refs = med.get("source_segment_refs") or med.get("source_segment_ids") or []
        roles: list[str] = []
        texts: list[str] = []
        if refs and segment_map:
            for r in refs:
                if r in segment_map:
                    roles.append(str(segment_map[r].get("role", "")).upper())
                    texts.append(str(segment_map[r].get("text", "")))

        is_patient_only = bool(roles and all(r in ("PATIENT", "ATTENDANT", "FAMILY") for r in roles))

        has_doctor_inquiry = False
        is_doctor_prescribed = False
        if any(r in ("DOCTOR", "PHYSICIAN", "CLINICIAN") for r in roles):
            for t in texts:
                tl = t.lower()
                is_inq = (
                    any(q in tl for q in ["did you take", "have you taken", "are you taking", "what medicine", "which tablet", "any painkillers"])
                    or tl.rstrip().endswith("?")
                )
                is_rx = any(p in tl for p in [
                    "prescrib", "start taking", "start tab", "i will give", "take tablet",
                    "take this", "tab ", "cap ", "1-0-1", "twice daily", "once daily", "for 5 days", "for 3 days", "for 7 days"
                ])
                if is_inq and not is_rx:
                    has_doctor_inquiry = True
                if is_rx:
                    is_doctor_prescribed = True

        is_in_prior_text = (med_lower in curr_med_text) or (med_lower in tx_hist_text) or (med_lower in hpi_text)
        is_in_plan_text = bool(full_plan_text and re.search(r"\b" + re.escape(med_lower) + r"\b", full_plan_text, re.IGNORECASE))

        detail = str(med.get("detail") or "")
        has_prior_phrase = any(p in detail.lower() for p in prior_phrases) or any(any(p in t.lower() for p in prior_phrases) for t in texts)

        # Exclude patient prior medications
        if (is_patient_only or has_doctor_inquiry or has_prior_phrase or (is_in_prior_text and not is_in_plan_text)) and not (is_in_plan_text or is_doctor_prescribed):
            continue

        dosage, freq, route, duration = parse_sig(detail)

        # If detail was generic, look into the specific clause in plan text
        if dosage == "As directed" or freq == "As prescribed" or duration == "As directed":
            if full_plan_text:
                clauses = re.split(r"[\.\n;]", full_plan_text)
                for cl in clauses:
                    if re.search(r"\b" + re.escape(med_lower) + r"\b", cl, re.IGNORECASE):
                        d2, f2, r2, dur2 = parse_sig(cl)
                        if dosage == "As directed" and d2 != "As directed":
                            dosage = d2
                        if freq == "As prescribed" and f2 != "As prescribed":
                            freq = f2
                        if duration == "As directed" and dur2 != "As directed":
                            duration = dur2
                        if route == "Oral" and r2 != "Oral":
                            route = r2

        seen_drugs.add(med_lower)
        prescriptions.append({
            "date": appt_date,
            "drug_name": med_val.title(),
            "dosage": dosage,
            "frequency": freq,
            "route": route,
            "duration": duration,
        })

    # 2. Also check if plan has explicit prescription lines for drugs not in entities
    rx_section_text = full_plan_text
    match_rx_sec = re.search(r"(?:prescriptions?(?:\s*/\s*medication\s+management)?:?|rx:?)(.*?)(?:diagnostic orders|investigations|follow-up|precautions|$)", full_plan_text, re.IGNORECASE | re.DOTALL)
    if match_rx_sec:
        rx_section_text = match_rx_sec.group(1)

    items = re.split(r"(?:[\r\n;]+|\d+\.\s*|,\s*(?=[A-Z]))", rx_section_text)
    for item in items:
        item = item.strip()
        if not item or len(item) < 3:
            continue
        has_med_marker = bool(re.search(r"\b(tab|tablet|cap|capsule|syr|syrup|inj|injection|oint|ointment|mg|g|mcg|ml|daily|tds|bd|od|sos|1-0-1)\b", item, re.IGNORECASE))
        if not has_med_marker:
            continue

        dosage, freq, route, duration = parse_sig(item)

        name_clean = item
        dm = re.search(dose_pattern, item, re.IGNORECASE)
        if dm:
            name_clean = name_clean.replace(dm.group(0), "")
        fm = re.search(freq_pattern, item, re.IGNORECASE)
        if fm:
            name_clean = name_clean.replace(fm.group(0), "")
        durm = re.search(dur_pattern, item, re.IGNORECASE)
        if durm:
            name_clean = name_clean.replace(durm.group(0), "")

        name_clean = re.sub(r"^(?:care\s+plan:?|prescriptions?(?:\s*/\s*medication\s+management)?:?|rx:?|take|start|prescribed?|tab(?:\.|\b)|tablet|cap(?:\.|\b)|capsule|syr(?:\.|\b)|syrup|inj(?:\.|\b)|injection)\s+", "", name_clean, flags=re.IGNORECASE)
        name_clean = re.sub(r"\b(?:prescribe|prescribed|advised|advise|to take)\b", "", name_clean, flags=re.IGNORECASE)
        name_clean = re.sub(r"\b(?:for|oral|orally|po|before food|after food|at bedtime|before breakfast)\b.*$", "", name_clean, flags=re.IGNORECASE)
        name_clean = re.sub(r"[^\w\s-]", "", name_clean).strip()

        if len(name_clean) >= 2 and not name_clean.lower() in ("prescriptions", "care plan", "medication management", "care", "plan", "evaluation"):
            key = name_clean.lower()
            if not any(key in d or d in key for d in seen_drugs):
                seen_drugs.add(key)
                prescriptions.append({
                    "date": appt_date,
                    "drug_name": name_clean.title(),
                    "dosage": dosage,
                    "frequency": freq,
                    "route": route,
                    "duration": duration,
                })

    return prescriptions


def _extract_doctor_orders(
    content: dict[str, Any],
    entities: list[dict[str, Any]],
    segments: list[dict[str, Any]],
    appt_date: str,
) -> list[dict[str, str]]:
    """Extract ONLY doctor-ordered investigations and procedures for this visit.
    
    Excludes past investigations told by the patient (which belong in Previous Investigation).
    """
    segment_map = {str(s.get("ref")): s for s in segments if s.get("ref")}

    plan_sec = content.get("plan") or {}
    plan_text = str(plan_sec.get("text") or "").strip()
    prev_inv_sec = content.get("previous_investigation") or {}
    prev_inv_text = str(prev_inv_sec.get("text") or "").lower()

    prior_phrases = [
        "done last", "done previously", "already done", "previous report",
        "past mri", "normal in last", "scanned earlier", "reports from last"
    ]

    orders: list[dict[str, str]] = []
    seen_orders: set[str] = set()

    inv_entities = [e for e in entities if str(e.get("entity_type")).upper() in ("INVESTIGATION", "PROCEDURE") and e.get("value")]

    for inv in inv_entities:
        val = str(inv.get("value") or "").strip()
        if not val:
            continue
        val_lower = val.lower()
        if val_lower in seen_orders:
            continue

        status = str(inv.get("status", "")).upper()
        if status in ("HISTORICAL", "NEGATED", "PAST"):
            continue

        refs = inv.get("source_segment_refs") or inv.get("source_segment_ids") or []
        roles: list[str] = []
        texts: list[str] = []
        if refs and segment_map:
            for r in refs:
                if r in segment_map:
                    roles.append(str(segment_map[r].get("role", "")).upper())
                    texts.append(str(segment_map[r].get("text", "")))

        is_patient_only = bool(roles and all(r in ("PATIENT", "ATTENDANT", "FAMILY") for r in roles))

        detail = str(inv.get("detail") or "")
        has_prior_phrase = any(p in detail.lower() for p in prior_phrases) or any(any(p in t.lower() for p in prior_phrases) for t in texts)

        is_in_prev_inv = val_lower in prev_inv_text
        is_in_plan = bool(plan_text and re.search(r"\b" + re.escape(val_lower) + r"\b", plan_text, re.IGNORECASE))

        if (is_patient_only or has_prior_phrase or (is_in_prev_inv and not is_in_plan)) and not is_in_plan:
            continue

        seen_orders.add(val_lower)
        purpose = detail if (detail and detail.lower() != "none" and not detail.lower().startswith("eg:")) else "Diagnostic evaluation"
        orders.append({
            "date": appt_date,
            "order_type": "Lab / Diagnostic",
            "order_name": val.title(),
            "purpose": purpose,
        })

    return orders


# ----------------------------------------------------------------------- PDF
def export_pdf(payload: dict[str, Any]) -> bytes:
    """Render the encounter to a PDF matching SIMS Hospital Ambulatory Care Clinical Notes."""
    from pathlib import Path
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        HRFlowable,
        Image,
        KeepTogether,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    session = payload.get("session", {})
    note = payload.get("clinical_note", {})
    content = note.get("content", {})
    entities: list[dict[str, Any]] = payload.get("clinical_entities", [])
    segments: list[dict[str, Any]] = payload.get("transcript", [])

    # Date formatting
    started_at = session.get("started_at") or session.get("created_at")
    appt_date = _format_display_date(started_at)
    print_date = datetime.now(timezone.utc).strftime("%b %d, %Y")

    # Demographic & encounter details
    hh_no = str(session.get("patient_id") or session.get("reference") or "HH-6838").strip()
    explicit_patient_name = session.get("patient_name")
    if explicit_patient_name and str(explicit_patient_name).strip():
        patient_name = str(explicit_patient_name).strip()
    else:
        raw_name = str(session.get("name") or "").strip()
        lower_raw = raw_name.lower()
        if (
            not raw_name
            or lower_raw.startswith("outpatient")
            or lower_raw.startswith("inpatient")
            or lower_raw.startswith("google meet")
            or lower_raw.startswith("telehealth")
            or lower_raw.startswith("sim-pt")
            or "consultation" in lower_raw
            or "meeting" in lower_raw
        ):
            patient_name = str(session.get("patient_id") or "Patient").strip()
        else:
            patient_name = raw_name

    gender = session.get("patient_gender") or session.get("gender") or "Male"
    age = session.get("patient_age") or session.get("age") or "48 Yrs"
    consult_name = session.get("doctor_name") or "Sims Hospital"
    speciality = session.get("speciality") or "Doctor"

    styles = getSampleStyleSheet()
    navy_dark = colors.HexColor("#1e3a8a")
    navy_header = colors.HexColor("#0f2942")
    slate_dark = colors.HexColor("#1e293b")
    text_muted = colors.HexColor("#64748b")
    bullet_pink = colors.HexColor("#e11d48")

    doc_title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10.5,
        leading=13,
        textColor=navy_header,
        alignment=TA_CENTER,
        spaceBefore=4,
        spaceAfter=8,
    )
    meta_label_style = ParagraphStyle(
        "MetaLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=11,
        textColor=slate_dark,
    )
    meta_val_style = ParagraphStyle(
        "MetaVal",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=slate_dark,
    )
    sec_heading_style = ParagraphStyle(
        "SecHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=slate_dark,
        spaceBefore=4,
        spaceAfter=2,
    )
    sec_body_style = ParagraphStyle(
        "SecBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#334155"),
        spaceAfter=4,
    )
    table_header_style = ParagraphStyle(
        "THeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=7.8,
        leading=10,
        textColor=slate_dark,
    )
    table_cell_style = ParagraphStyle(
        "TCell",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=7.6,
        leading=10,
        textColor=colors.HexColor("#475569"),
    )
    footer_style = ParagraphStyle(
        "FooterText",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=7.2,
        leading=9,
        textColor=text_muted,
    )

    buffer = io.BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=14 * mm,
        rightMargin=14 * mm,
        topMargin=10 * mm,
        bottomMargin=12 * mm,
        title=f"SIMS Hospital - {hh_no}",
        author="SIMS Hospital Chennai",
    )

    story: list[Any] = []

    # 1. Header with SIMS Hospital Logo or Styled Navy Banner
    logo_path = Path(__file__).resolve().parent.parent.parent / "assets" / "sims_logo.png"
    if logo_path.exists():
        try:
            story.append(Image(str(logo_path), width=54 * mm, height=18 * mm))
            story.append(Spacer(1, 2 * mm))
        except Exception:
            pass
    else:
        # Styled Navy Header Bar fallback
        header_table = Table(
            [[Paragraph("<font color='white'><b>SIMS HOSPITAL</b><br/><font size='7.5'>CHENNAI</font></font>", ParagraphStyle("Hdr", alignment=TA_CENTER))]],
            colWidths=[182 * mm],
        )
        header_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#1e3a8a")),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ])
        )
        story.append(header_table)
        story.append(Spacer(1, 2 * mm))

    story.append(Paragraph("AMBULATORY CARE - CLINICAL NOTES", doc_title_style))

    # 2. Patient & Encounter Metadata Grid (2-column layout matching reference PDF)
    meta_data = [
        [
            Paragraph("Appointment Date & Time", meta_label_style),
            Paragraph(f": {appt_date}", meta_val_style),
            Paragraph("Print Date Time", meta_label_style),
            Paragraph(f": {print_date}", meta_val_style),
        ],
        [
            Paragraph("HH No.", meta_label_style),
            Paragraph(f": {hh_no}", meta_val_style),
            Paragraph("Patient Name", meta_label_style),
            Paragraph(f": {patient_name}", meta_val_style),
        ],
        [
            Paragraph("Gender", meta_label_style),
            Paragraph(f": {gender}", meta_val_style),
            Paragraph("Age", meta_label_style),
            Paragraph(f": {age}", meta_val_style),
        ],
        [
            Paragraph("Consult Name", meta_label_style),
            Paragraph(f": {consult_name}", meta_val_style),
            Paragraph("Speciality", meta_label_style),
            Paragraph(f": {speciality}", meta_val_style),
        ],
    ]

    meta_table = Table(meta_data, colWidths=[42 * mm, 49 * mm, 38 * mm, 53 * mm])
    meta_table.setStyle(
        TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 1.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ])
    )
    story.append(meta_table)
    story.append(Spacer(1, 3.5 * mm))

    # 3. The 13 Standard Ambulatory Care Sections
    AMBULATORY_SECTIONS = [
        ("Presenting Complaint", ["chief_complaint"]),
        ("History of Present Illness", ["history_of_present_illness"]),
        ("Past History", ["relevant_medical_history", "past_history"]),
        ("Social History", ["social_history"]),
        ("Family History", ["family_history"]),
        ("Menstrual History", ["menstrual_history"]),
        ("Physical Examination", ["physical_examination", "examination", "vitals"]),
        ("Current Medication", ["current_medication"]),
        ("Allergies", ["allergies"]),
        ("Treatment History", ["treatment_history"]),
        ("Previous Investigation", ["previous_investigation"]),
        ("Assessment and Plan", ["assessment"]),
        ("Plan Of Care", ["plan", "follow_up"]),
    ]

    # Pre-extract entities for quick section synthesis if not present in note content
    med_entities = [e.get("value") for e in entities if str(e.get("entity_type")).upper() == "MEDICATION" and e.get("value")]
    allergy_entities = [e.get("value") for e in entities if str(e.get("entity_type")).upper() == "ALLERGY" and e.get("value")]
    inv_entities = [e.get("value") for e in entities if str(e.get("entity_type")).upper() in ("INVESTIGATION", "PROCEDURE") and e.get("value")]

    for label, keys in AMBULATORY_SECTIONS:
        text = ""
        for key in keys:
            sec = content.get(key) or {}
            val = str(sec.get("text") or "").strip()
            if val and val.lower() not in _UNDOCUMENTED_PHRASES:
                text = f"{text} {val}".strip() if text else val

        if not text:
            if label == "Current Medication" and med_entities:
                text = ", ".join(med_entities)
            elif label == "Allergies" and allergy_entities:
                text = ", ".join(allergy_entities)
            elif label == "Previous Investigation" and inv_entities:
                text = ", ".join(inv_entities)
            else:
                text = "---"

        # Pink circular badge icon with bold section heading
        sec_header_text = f"<font color='#e11d48' size='9'>&#9679;</font> &nbsp;<b>{label}</b>"
        story.append(Paragraph(sec_header_text, sec_heading_style))
        story.append(Paragraph(text, sec_body_style))

    story.append(Spacer(1, 2 * mm))

    # 4. Prescription Table
    story.append(Paragraph("<b>Prescription</b>", sec_heading_style))
    rx_rows = [[
        Paragraph("Date", table_header_style),
        Paragraph("Drug Names", table_header_style),
        Paragraph("Dosage", table_header_style),
        Paragraph("Frequency/Mode", table_header_style),
        Paragraph("Route", table_header_style),
        Paragraph("Duration", table_header_style),
    ]]

    rx_prescriptions = _extract_doctor_prescriptions(content, entities, segments, appt_date)
    if rx_prescriptions:
        for rx in rx_prescriptions:
            rx_rows.append([
                Paragraph(rx.get("date", appt_date), table_cell_style),
                Paragraph(rx.get("drug_name", ""), table_cell_style),
                Paragraph(rx.get("dosage", "As directed"), table_cell_style),
                Paragraph(rx.get("frequency", "As prescribed"), table_cell_style),
                Paragraph(rx.get("route", "Oral"), table_cell_style),
                Paragraph(rx.get("duration", "As directed"), table_cell_style),
            ])
        rx_table_style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
            ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#cbd5e1")),
            ("LINEBELOW", (0, 1), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 2.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]
    else:
        # Cleanly show that no new medications were prescribed in this visit
        rx_rows.append([
            Paragraph(appt_date, table_cell_style),
            Paragraph("<font color='#64748b'><i>No new medications prescribed by physician during this encounter.</i></font>", table_cell_style),
            Paragraph("", table_cell_style),
            Paragraph("", table_cell_style),
            Paragraph("", table_cell_style),
            Paragraph("", table_cell_style),
        ])
        rx_table_style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
            ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#cbd5e1")),
            ("LINEBELOW", (0, 1), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
            ("SPAN", (1, 1), (-1, 1)),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]

    rx_table = Table(rx_rows, colWidths=[24 * mm, 46 * mm, 28 * mm, 32 * mm, 26 * mm, 26 * mm])
    rx_table.setStyle(TableStyle(rx_table_style))
    story.append(rx_table)
    story.append(Spacer(1, 3 * mm))

    # 5. Order Table
    story.append(Paragraph("<b>Order</b>", sec_heading_style))
    order_rows = [[
        Paragraph("Date", table_header_style),
        Paragraph("Order Type", table_header_style),
        Paragraph("Order Name", table_header_style),
        Paragraph("Purpose", table_header_style),
    ]]

    doc_orders = _extract_doctor_orders(content, entities, segments, appt_date)
    if doc_orders:
        for order in doc_orders:
            order_rows.append([
                Paragraph(order.get("date", appt_date), table_cell_style),
                Paragraph(order.get("order_type", "Lab / Diagnostic"), table_cell_style),
                Paragraph(order.get("order_name", ""), table_cell_style),
                Paragraph(order.get("purpose", "Diagnostic evaluation"), table_cell_style),
            ])
        order_table_style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
            ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#cbd5e1")),
            ("LINEBELOW", (0, 1), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 2.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]
    else:
        # Cleanly show that no diagnostic investigations were ordered in this visit
        order_rows.append([
            Paragraph(appt_date, table_cell_style),
            Paragraph("<font color='#64748b'><i>No diagnostic investigations or procedures ordered during this encounter.</i></font>", table_cell_style),
            Paragraph("", table_cell_style),
            Paragraph("", table_cell_style),
        ])
        order_table_style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
            ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#cbd5e1")),
            ("LINEBELOW", (0, 1), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
            ("SPAN", (1, 1), (-1, 1)),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]

    order_table = Table(order_rows, colWidths=[26 * mm, 44 * mm, 52 * mm, 60 * mm])
    order_table.setStyle(TableStyle(order_table_style))
    story.append(order_table)
    story.append(Spacer(1, 6 * mm))

    # 6. Official Hospital Sign-off Footer
    footer_data = [[
        Paragraph("CONSULTANT SIGNATURE", footer_style),
        Paragraph("HH CONFIDENTIAL", ParagraphStyle("FCenter", parent=footer_style, alignment=TA_CENTER)),
        Paragraph("PLEASE SIGN ALL ENTRIES.", ParagraphStyle("FRight", parent=footer_style, alignment=TA_RIGHT)),
    ]]
    footer_table = Table(footer_data, colWidths=[60 * mm, 62 * mm, 60 * mm])
    footer_table.setStyle(
        TableStyle([
            ("LINEABOVE", (0, 0), (-1, 0), 0.5, colors.HexColor("#94a3b8")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ])
    )
    story.append(footer_table)

    document.build(story)
    return buffer.getvalue()


def _format_display_date(date_val: Any) -> str:
    if not date_val:
        return datetime.now(timezone.utc).strftime("%b %d, %Y")
    if isinstance(date_val, datetime):
        return date_val.strftime("%b %d, %Y")
    try:
        dt = datetime.fromisoformat(str(date_val).replace("Z", "+00:00"))
        return dt.strftime("%b %d, %Y")
    except Exception:
        return datetime.now(timezone.utc).strftime("%b %d, %Y")


def _format_timestamp(seconds: float) -> str:
    seconds = max(0.0, float(seconds or 0))
    minutes, secs = divmod(int(seconds), 60)
    hours, minutes = divmod(minutes, 60)
    return f"{hours:02d}:{minutes:02d}:{secs:02d}"


# ---------------------------------------------------------------------- FHIR
class FHIRAdapter:
    """Maps a MedScribe session onto a FHIR-compatible R4 bundle."""

    OBSERVATION_TYPES = {
        EntityType.SYMPTOM,
        EntityType.FINDING,
        EntityType.SEVERITY,
        EntityType.FREQUENCY,
        EntityType.DURATION,
        EntityType.CHARACTER,
    }

    def build_bundle(
        self,
        *,
        session: dict[str, Any],
        note: dict[str, Any],
        entities: list[dict[str, Any]],
        segments: list[dict[str, Any]],
    ) -> dict[str, Any]:
        patient_id = f"patient-{_slug(session.get('patient_id', 'sim'))}"
        encounter_id = f"encounter-{_slug(session.get('reference', 'sim'))}"
        recorded = note.get("updated_at") or datetime.now(timezone.utc).isoformat()

        resources: list[dict[str, Any]] = [
            self._patient(patient_id, session),
            self._encounter(encounter_id, patient_id, session),
        ]

        for entity in entities:
            entity_type = _as_entity_type(entity.get("entity_type"))
            if entity_type is None:
                continue
            if entity_type in self.OBSERVATION_TYPES:
                resources.append(self._observation(entity, patient_id, encounter_id, recorded))
            elif entity_type is EntityType.MEDICATION:
                resources.append(self._medication_statement(entity, patient_id, encounter_id, recorded))
            elif entity_type is EntityType.ALLERGY:
                resources.append(self._allergy(entity, patient_id, recorded))
            elif entity_type is EntityType.INVESTIGATION:
                resources.append(self._service_request(entity, patient_id, encounter_id, recorded))
            elif entity_type in (EntityType.PLAN, EntityType.FOLLOW_UP):
                resources.append(self._care_plan(entity, patient_id, encounter_id, recorded))

        resources.append(self._diagnostic_report(note, patient_id, encounter_id, recorded, len(segments)))

        return {
            "resourceType": "Bundle",
            "id": f"medscribe-{_slug(session.get('reference', 'sim'))}",
            "type": "collection",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "meta": {
                "profile": [],
                "tag": [
                    {"system": "http://medscribe.local/tags", "code": "encounter", "display": "Clinical encounter"},
                    {
                        "system": "http://medscribe.local/tags",
                        "code": "fhir-compatible",
                        "display": f"FHIR {FHIR_VERSION} compatible subset - not conformance validated",
                    },
                ],
            },
            "entry": [{"fullUrl": f"urn:uuid:{uuid.uuid4()}", "resource": resource} for resource in resources],
        }

    # ------------------------------------------------------------- resources
    @staticmethod
    def _patient(patient_id: str, session: dict[str, Any]) -> dict[str, Any]:
        return {
            "resourceType": "Patient",
            "id": patient_id,
            "identifier": [
                {
                    "system": "http://medscribe.local/patient",
                    "value": str(session.get("patient_id", "unknown")),
                }
            ],
            "active": True,
            "name": [{"use": "anonymous", "text": "Patient"}],
        }

    @staticmethod
    def _encounter(encounter_id: str, patient_id: str, session: dict[str, Any]) -> dict[str, Any]:
        return {
            "resourceType": "Encounter",
            "id": encounter_id,
            "status": "finished" if session.get("ended_at") else "in-progress",
            "class": {
                "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
                "code": "AMB",
                "display": "ambulatory",
            },
            "subject": {"reference": f"Patient/{patient_id}"},
            "period": {"start": session.get("started_at"), "end": session.get("ended_at")},
            "reasonCode": [{"text": session.get("scenario") or "Clinical encounter"}],
        }

    @staticmethod
    def _observation(
        entity: dict[str, Any], patient_id: str, encounter_id: str, recorded: str
    ) -> dict[str, Any]:
        status = str(entity.get("status", "UNKNOWN"))
        resource = {
            "resourceType": "Observation",
            "id": f"observation-{_slug(entity.get('ref', uuid.uuid4().hex))}",
            "status": "preliminary",
            "category": [
                {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                            "code": "exam",
                        }
                    ]
                }
            ],
            "code": _codeable(entity),
            "subject": {"reference": f"Patient/{patient_id}"},
            "encounter": {"reference": f"Encounter/{encounter_id}"},
            "effectiveDateTime": recorded,
            "note": [{"text": _provenance_text(entity)}],
        }
        if status == "NEGATED":
            resource["valueCodeableConcept"] = {
                "coding": [{"system": "http://terminology.hl7.org/CodeSystem/v2-0136", "code": "N"}],
                "text": "Explicitly denied by the speaker",
            }
        elif status == "UNCERTAIN":
            resource["dataAbsentReason"] = {"text": "Uncertain - hedged statement, not confirmed"}
        return resource

    @staticmethod
    def _medication_statement(
        entity: dict[str, Any], patient_id: str, encounter_id: str, recorded: str
    ) -> dict[str, Any]:
        return {
            "resourceType": "MedicationStatement",
            "id": f"medication-{_slug(entity.get('ref', uuid.uuid4().hex))}",
            "status": "recorded" if str(entity.get("status")) != "NEGATED" else "not-taken",
            "medicationCodeableConcept": _codeable(entity),
            "subject": {"reference": f"Patient/{patient_id}"},
            "context": {"reference": f"Encounter/{encounter_id}"},
            "dateAsserted": recorded,
            "note": [{"text": _provenance_text(entity)}],
        }

    @staticmethod
    def _allergy(entity: dict[str, Any], patient_id: str, recorded: str) -> dict[str, Any]:
        negated = str(entity.get("status")) == "NEGATED"
        return {
            "resourceType": "AllergyIntolerance",
            "id": f"allergy-{_slug(entity.get('ref', uuid.uuid4().hex))}",
            "clinicalStatus": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
                        "code": "inactive" if negated else "active",
                    }
                ]
            },
            "verificationStatus": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification",
                        "code": "refuted" if negated else "unconfirmed",
                    }
                ]
            },
            "code": _codeable(entity),
            "patient": {"reference": f"Patient/{patient_id}"},
            "recordedDate": recorded,
            "note": [{"text": _provenance_text(entity)}],
        }

    @staticmethod
    def _service_request(
        entity: dict[str, Any], patient_id: str, encounter_id: str, recorded: str
    ) -> dict[str, Any]:
        return {
            "resourceType": "ServiceRequest",
            "id": f"servicerequest-{_slug(entity.get('ref', uuid.uuid4().hex))}",
            "status": "draft",
            "intent": "proposal",
            "code": _codeable(entity),
            "subject": {"reference": f"Patient/{patient_id}"},
            "encounter": {"reference": f"Encounter/{encounter_id}"},
            "authoredOn": recorded,
            "note": [{"text": _provenance_text(entity)}],
        }

    @staticmethod
    def _care_plan(
        entity: dict[str, Any], patient_id: str, encounter_id: str, recorded: str
    ) -> dict[str, Any]:
        return {
            "resourceType": "CarePlan",
            "id": f"careplan-{_slug(entity.get('ref', uuid.uuid4().hex))}",
            "status": "draft",
            "intent": "proposal",
            "title": str(entity.get("entity_type", "PLAN")).replace("_", " ").title(),
            "description": str(entity.get("value", "")),
            "subject": {"reference": f"Patient/{patient_id}"},
            "encounter": {"reference": f"Encounter/{encounter_id}"},
            "created": recorded,
            "note": [{"text": _provenance_text(entity)}],
        }

    @staticmethod
    def _diagnostic_report(
        note: dict[str, Any], patient_id: str, encounter_id: str, recorded: str, segment_count: int
    ) -> dict[str, Any]:
        content = note.get("content", {})
        lines = []
        for key in SECTION_KEYS:
            section = content.get(key) or {}
            if not _section_documented(section):
                continue
            lines.append(f"{SECTION_LABELS[key]}: {section.get('text')}")
        narrative = "<div xmlns=\"http://www.w3.org/1999/xhtml\">" + "".join(
            f"<p>{_escape(line)}</p>" for line in lines
        ) + f"<p><em>{_escape(DISCLAIMER)}</em></p></div>"
        return {
            "resourceType": "DiagnosticReport",
            "id": f"report-{_slug(str(note.get('id', uuid.uuid4().hex)))}",
            "status": "preliminary" if str(note.get("status")) != "APPROVED" else "final",
            "code": {"text": "AI-assisted clinical documentation"},
            "subject": {"reference": f"Patient/{patient_id}"},
            "encounter": {"reference": f"Encounter/{encounter_id}"},
            "issued": recorded,
            "conclusion": (
                (content.get("assessment") or {}).get("text")
                if _section_documented(content.get("assessment"))
                else None
            ),
            "text": {"status": "generated", "div": narrative},
            "extension": [
                {
                    "url": "http://medscribe.local/StructureDefinition/transcript-segment-count",
                    "valueInteger": segment_count,
                },
                {
                    "url": "http://medscribe.local/StructureDefinition/note-version",
                    "valueInteger": int(note.get("version") or 0),
                },
            ],
        }


def _codeable(entity: dict[str, Any]) -> dict[str, Any]:
    """Only emit a coding when a verified code exists - never fabricate one."""
    text = str(entity.get("normalized_value") or entity.get("value") or "")
    code = entity.get("normalized_code")
    system = entity.get("terminology_system")
    if code and system:
        return {"coding": [{"system": _system_url(system), "code": code, "display": text}], "text": text}
    return {"text": text}


def _system_url(system: str) -> str:
    return {
        "SNOMED-CT": "http://snomed.info/sct",
        "ICD-10": "http://hl7.org/fhir/sid/icd-10",
        "RxNorm": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "LOINC": "http://loinc.org",
    }.get(system, f"http://medscribe.local/{_slug(system)}")


def _provenance_text(entity: dict[str, Any]) -> str:
    refs = ", ".join(entity.get("source_segment_refs") or []) or "none"
    return (
        f"Status: {entity.get('status')}. Extraction confidence: "
        f"{float(entity.get('confidence') or 0) * 100:.0f}%. Transcript evidence: {refs}. "
        "Requires human review."
    )


def _as_entity_type(value: Any) -> EntityType | None:
    if isinstance(value, EntityType):
        return value
    try:
        return EntityType(str(value))
    except ValueError:
        return None


def _slug(value: Any) -> str:
    text = str(value).lower()
    return "".join(char if char.isalnum() else "-" for char in text).strip("-") or "unknown"


def _escape(value: str) -> str:
    return (
        value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )


def note_status_is_approved(note: dict[str, Any]) -> bool:
    return str(note.get("status")) == "APPROVED"


def entity_status_label(status: Any) -> str:
    try:
        return EntityStatus(str(status)).value
    except ValueError:
        return "UNKNOWN"


def empty_note_content() -> dict[str, Any]:
    return ClinicalNoteContent().model_dump(mode="json")
