/** Synthetic fixtures mirroring the reference demo conversation. */

import type {
  ClinicalEntity,
  ClinicalNote,
  ClinicalSection,
  EvidenceLink,
  Session,
  Speaker,
  TranscriptSegment,
} from '@/types'

export const speakers: Speaker[] = [
  { id: 'sp-0', label: 'speaker_0', display_name: null, role: 'DOCTOR', confidence: 0.93, role_source: 'SYSTEM' },
  { id: 'sp-1', label: 'speaker_1', display_name: null, role: 'PATIENT', confidence: 0.91, role_source: 'SYSTEM' },
]

export const segments: TranscriptSegment[] = [
  {
    id: 'seg-uuid-1',
    ref: 'seg_001',
    sequence: 1,
    speaker_id: 'sp-0',
    speaker_label: 'speaker_0',
    role: 'DOCTOR',
    text: 'Good morning. What brings you in today?',
    start_time: 0,
    end_time: 3.4,
    confidence: 0.96,
    asr_confidence: 0.96,
    diarization_confidence: 0.93,
    overlapping: false,
    is_final: true,
  },
  {
    id: 'seg-uuid-2',
    ref: 'seg_002',
    sequence: 2,
    speaker_id: 'sp-1',
    speaker_label: 'speaker_1',
    role: 'PATIENT',
    text: "I've been having chest discomfort since yesterday evening.",
    start_time: 3.6,
    end_time: 8.1,
    confidence: 0.94,
    asr_confidence: 0.94,
    diarization_confidence: 0.91,
    overlapping: false,
    is_final: true,
  },
  {
    id: 'seg-uuid-3',
    ref: 'seg_003',
    sequence: 3,
    speaker_id: 'sp-1',
    speaker_label: 'speaker_1',
    role: 'PATIENT',
    text: "No, I don't have any shortness of breath.",
    start_time: 9.0,
    end_time: 12.2,
    confidence: 0.92,
    asr_confidence: 0.92,
    diarization_confidence: 0.9,
    overlapping: false,
    is_final: true,
  },
]

export const entities: ClinicalEntity[] = [
  {
    id: 'ent-1',
    ref: 'ent_001',
    entity_type: 'SYMPTOM',
    value: 'chest discomfort',
    normalized_value: 'chest discomfort',
    normalized_code: null,
    terminology_system: 'SNOMED CT',
    status: 'PRESENT',
    confidence: 0.93,
    source_segment_refs: ['seg_002'],
    detail: 'since yesterday evening',
    review_required: false,
    review_reason: null,
    evidence: [],
  },
  {
    id: 'ent-2',
    ref: 'ent_002',
    entity_type: 'SYMPTOM',
    value: 'shortness of breath',
    normalized_value: 'shortness of breath',
    normalized_code: null,
    terminology_system: 'SNOMED CT',
    status: 'NEGATED',
    confidence: 0.95,
    source_segment_refs: ['seg_003'],
    detail: null,
    review_required: false,
    review_reason: null,
    evidence: [],
  },
]

function section(text: string, evidenceRefs: string[] = ['seg_002']): ClinicalSection {
  return {
    text,
    confidence: 0.9,
    evidence: evidenceRefs.map((ref) => ({
      transcript_segment_ref: ref,
      speaker_label: 'speaker_1',
      speaker_role: 'PATIENT',
      timestamp: 3.6,
      confidence: 0.94,
      source_text: "I've been having chest discomfort since yesterday evening.",
      validated: true,
      validation_error: null,
    })),
    review_required: false,
    review_reason: null,
    edited_by_human: false,
  }
}

export const note: ClinicalNote = {
  id: 'note-1',
  session_id: 'session-1',
  status: 'DRAFT',
  version: 2,
  content: {
    chief_complaint: section('Chest discomfort since yesterday evening.'),
    history_of_present_illness: section('Patient reports intermittent pressure-like chest discomfort.'),
    relevant_medical_history: section('Not mentioned', []),
    social_history: section('Not mentioned', []),
    family_history: section('Not mentioned', []),
    menstrual_history: section('Not mentioned', []),
    physical_examination: section('Not mentioned', []),
    current_medication: section('Not mentioned', []),
    allergies: section('Not mentioned', []),
    treatment_history: section('Not mentioned', []),
    previous_investigation: section('Not mentioned', []),
    assessment: section('Pending clinical evaluation', []),
    plan: section('Not mentioned', []),
    follow_up: section('Not mentioned', []),
    symptoms: entities,
    medications: [],
    findings: [],
    investigations: [],
    generated_at: new Date().toISOString(),
    model: 'gemini-2.5-flash',
    version: 2,
  },
  review_flags: [],
  model: 'gemini-2.5-flash',
  approved_by: null,
  approved_at: null,
  exported_at: null,
  updated_at: new Date().toISOString(),
}

export const evidence: EvidenceLink[] = [
  {
    id: 'ev-1',
    target_kind: 'SECTION',
    target_key: 'chief_complaint',
    clinical_statement: 'Chest discomfort since yesterday evening.',
    segment_ref: 'seg_002',
    speaker_label: 'speaker_1',
    speaker_role: 'PATIENT',
    source_text: "I've been having chest discomfort since yesterday evening.",
    timestamp: 3.6,
    confidence: 0.94,
    validated: true,
    validation_error: null,
  },
]

export const session: Session = {
  id: 'session-1',
  reference: 'SIM-2026-001',
  name: 'Outpatient chest discomfort',
  patient_id: 'SIM-PT-0042',
  scenario: 'Standardised patient reporting chest discomfort',
  simulation_type: 'OUTPATIENT',
  doctor_name: 'Dr. A. Rao',
  faculty_name: 'Prof. M. Iyer',
  status: 'LIVE',
  mode: 'DEMO',
  audio_source: 'SIMULATION',
  ai_mode: 'gemini',
  model_name: 'gemini-2.5-flash',
  started_at: new Date().toISOString(),
  ended_at: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  last_error: null,
  duration_seconds: 42,
  segment_count: 3,
  entity_count: 2,
  note_status: 'DRAFT',
  note_version: 2,
  speakers,
}
