"""initial medscribe schema

Revision ID: f3565cf9301b
Revises: 
Create Date: 2026-08-18 18:50:17.029748
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f3565cf9301b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('DOCTOR', 'STUDENT', 'FACULTY', 'ADMIN', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('sessions',
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('simulation_type', sa.Enum('OSCE', 'WARD_ROUND', 'OUTPATIENT', 'EMERGENCY', 'TEACHING', 'OTHER', name='simulationtype', native_enum=False, length=32), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=True),
    sa.Column('faculty_id', sa.Uuid(), nullable=True),
    sa.Column('doctor_name', sa.String(length=255), nullable=True),
    sa.Column('faculty_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'LIVE', 'PAUSED', 'PROCESSING', 'REVIEW', 'APPROVED', 'COMPLETED', name='sessionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('mode', sa.Enum('DEMO', 'MICROPHONE', 'UPLOAD', name='sessionmode', native_enum=False, length=32), nullable=False),
    sa.Column('audio_source', sa.Enum('MICROPHONE', 'UPLOAD', 'SIMULATION', name='audiosource', native_enum=False, length=32), nullable=False),
    sa.Column('ai_mode', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_seconds', sa.Float(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_status'), ['status'], unique=False)

    op.create_table('audio_chunks',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MICROPHONE', 'UPLOAD', 'SIMULATION', name='audiosource', native_enum=False, length=32), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('speech_ratio', sa.Float(), nullable=False),
    sa.Column('rms_dbfs', sa.Float(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_chunks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_chunks_session_id'), ['session_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_session_id'), ['session_id'], unique=False)

    op.create_table('clinical_entities',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.Enum('SYMPTOM', 'FINDING', 'MEDICATION', 'ALLERGY', 'DIAGNOSIS_MENTIONED', 'PROCEDURE', 'INVESTIGATION', 'DURATION', 'SEVERITY', 'FREQUENCY', 'CHARACTER', 'PLAN', 'FOLLOW_UP', 'MEDICAL_HISTORY', name='entitytype', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('normalized_value', sa.String(length=512), nullable=True),
    sa.Column('normalized_code', sa.String(length=64), nullable=True),
    sa.Column('terminology_system', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'NEGATED', 'UNCERTAIN', 'HISTORICAL', 'UNKNOWN', name='entitystatus', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_segment_refs', sa.JSON(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('extraction_model', sa.String(length=128), nullable=True),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_entities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_entities_ref'), ['ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_entities_session_id'), ['session_id'], unique=False)

    op.create_table('clinical_notes',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'DRAFT', 'REVIEW_REQUIRED', 'APPROVED', 'EXPORTED', name='notestatus', native_enum=False, length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('review_flags', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_notes_session_id'), ['session_id'], unique=False)

    op.create_table('speakers',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('DOCTOR', 'PATIENT', 'NURSE', 'STAFF', 'BACKGROUND', 'UNKNOWN', name='speakerrole', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('role_source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'label', name='uq_speaker_session_label')
    )
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speakers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_speakers_session_id'), ['session_id'], unique=False)

    op.create_table('note_versions',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'DRAFT', 'REVIEW_REQUIRED', 'APPROVED', 'EXPORTED', name='notestatus', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('changed_sections', sa.JSON(), nullable=False),
    sa.Column('author_type', sa.String(length=16), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_versions_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_versions_session_id'), ['session_id'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_id', sa.Uuid(), nullable=True),
    sa.Column('audio_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('ref', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('asr_confidence', sa.Float(), nullable=False),
    sa.Column('diarization_confidence', sa.Float(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('overlapping', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['audio_chunk_id'], ['audio_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'ref', name='uq_segment_session_ref')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_segments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_ref'), ['ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_session_id'), ['session_id'], unique=False)

    op.create_table('evidence_links',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_segment_id', sa.Uuid(), nullable=True),
    sa.Column('clinical_entity_id', sa.Uuid(), nullable=True),
    sa.Column('note_version_id', sa.Uuid(), nullable=True),
    sa.Column('target_kind', sa.String(length=16), nullable=False),
    sa.Column('target_key', sa.String(length=128), nullable=False),
    sa.Column('clinical_statement', sa.Text(), nullable=False),
    sa.Column('segment_ref', sa.String(length=32), nullable=True),
    sa.Column('speaker_label', sa.String(length=64), nullable=True),
    sa.Column('speaker_role', sa.String(length=32), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validation_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['clinical_entity_id'], ['clinical_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_version_id'], ['note_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_target_key'), ['target_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_links_target_key'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_session_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_id'))

    op.drop_table('evidence_links')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_session_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_segments_ref'))
        batch_op.drop_index(batch_op.f('ix_transcript_segments_id'))

    op.drop_table('transcript_segments')
    with op.batch_alter_table('note_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_versions_session_id'))
        batch_op.drop_index(batch_op.f('ix_note_versions_note_id'))
        batch_op.drop_index(batch_op.f('ix_note_versions_id'))

    op.drop_table('note_versions')
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speakers_session_id'))
        batch_op.drop_index(batch_op.f('ix_speakers_id'))

    op.drop_table('speakers')
    with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_notes_session_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_notes_id'))

    op.drop_table('clinical_notes')
    with op.batch_alter_table('clinical_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_entities_session_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_entities_ref'))
        batch_op.drop_index(batch_op.f('ix_clinical_entities_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_entities_entity_type'))

    op.drop_table('clinical_entities')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('audio_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_chunks_session_id'))
        batch_op.drop_index(batch_op.f('ix_audio_chunks_id'))

    op.drop_table('audio_chunks')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_sessions_reference'))
        batch_op.drop_index(batch_op.f('ix_sessions_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
